version: "3.1"

services:
  drupal:
    container_name: drupal
    image: drupal:latest
    secrets:
      - password
    environment:
      MYSQL_DATABASE: drupal
      MYSQL_USER: user
      MYSQL_PASSWORD: /run/secrets/password
    ports:
      - '8001:80'

secrets:
  password:
    external: true
